version: '3'

services:
  web:
    restart: always
    build: .
    container_name: dojo-web
    command: invoke release start
    volumes:
      - ./web:/src
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
    container_name: dojo-db
    ports:
      - "5432:5432"
