version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    container_name: dojo-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: dojo-web
    command: bash -c "python manage.py collectstatic --no-input; python manage.py migrate; gunicorn dojo.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./src:/src
    expose:
      - "8000"
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
    container_name: dojo-db
    ports:
      - "5432:5432"
