version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: dojo-nginx
    ports:
      - "8000:8000"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./src:/src
      - ./static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: dojo-web
    volumes:
      - ./code:/code
      - ./static:/static
    ports:
      - "8080:8080"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn dojo.wsgi -b 0.0.0.0:8080"
    depends_on:
      - db
  db:
    image: postgres
    container_name: dojo-db
    ports:
      - "5432:5432"
